### ISSUE TITLE
Supporting a glob pattern in options

### ISSUE THREAD

**Issue by rowanwins** [allex/rollup-plugin-webworkify#1]
Hi there, 

Thanks for a neat little plugin. 

I was wondering if it would be possible to add options to the plugin config that allowed you to pass in a glob pattern to test if something was a worker, rather than relying on prepending `worker#..`, this would provide comparable configuration as the [webpack worker-loader](https://github.com/webpack-contrib/worker-loader#config)

For example in my src code I'd write
````
import Worker from './decoder.worker';
````
And then in my rollup config I'd write
````
plugins: [
   webworkify({
     pattern: '*.worker.js'
   }) 
]
````
This would allow my source code to be less polluted by plugin-specific ways of doing things. What do you think?

**Comment by allex** [comment]
thanks for the great suggest. will be enhance in next release.

```js
// rollup.config.js --------

export default {
  entry: 'src/main.js',
  plugins: [
    webworkify({
      // specifically patten files
      pattern: '**/*.worker.js'  // Default: undefined (follow micromath globs)
    })
  ],
  format: 'umd'
};

//  ----
// ../lib/foo.worker.js ---------

// import work from 'worker#../lib/worker.js'
import work from '../lib/foo.worker.js'
...
```

**Comment by rowanwins** [comment]
Awesome - thanks @allex !
